version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      docker:
        patterns:
          - "*"
    labels:
      - dependencies
      - docker
